# Generated by Django 3.1.5 on 2021-01-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Язык программирования')),
                ('slug', models.CharField(blank=True, max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'язык программирования',
                'verbose_name_plural': 'Языки программирования',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Название населенного пункта',
                     'verbose_name_plural': 'Название населенных пунктов'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Название населенного пункта')
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, max_length=64, unique=True)
        ),
    ]

