# Generated by Django 3.1.5 on 2021-01-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'имя пользователя', 'verbose_name_plural': 'Имена пользователей'},
        ),
    ]
